# https://github.com/k1LoW/octocov?tab=readme-ov-file#configuration
coverage:
  paths:
    - coverage/lcov.info
  badge:
    path: docs/octocov/coverage.svg
codeToTestRatio:
  code:
    - '**/src/**/*.ts'
  test:
    - '**/src/**/*.spec.ts'
  badge:
    path: docs/octocov/ratio.svg
testExecutionTime:
  if: true
  badge:
    path: docs/octocov/time.svg
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
