export { sigmoid } from './sigmoid'
export { logOfBase, logFnOfBase } from './log'
export { sum, product, average } from './array'
export { clamp } from './clamp'
export { softmax, softmaxWithTemperature } from './softmax'
