name: Binary Release

on:
  push:
  release:
    # "released" events are emitted either when directly be released or be edited from pre-released.
    types: [prereleased, released]

jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - cmd: build:standalone:macos-arm64
            os: macos-latest
          - cmd: build:standalone:macos-x64
            os: macos-latest
          - cmd: build:standalone:win-arm64
            os: windows-latest
          - cmd: build:standalone:win-x64
            os: windows-latest
          - cmd: build:standalone:linux-arm64
            os: ubuntu-latest
          - cmd: build:standalone:linux-x64
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: yarn
          cache-dependency-path: yarn.lock

      - uses: actions/cache@v2
        with:
          path: ~/.pkg_cache
          key: ${{ runner.os }}-pkg-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-pkg-cache-

      - name: install and build
        env:
          PKG_CACHE_PATH: ~/.pkg_cache
        run: |
          # os is macos-latest
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            arch -arm64 yarn install
            arch -arm64 yarn build:lib
            arch -arm64 yarn build:bin
            arch -arm64 yarn "${{ matrix.cmd }}" 
          else
            yarn install
            yarn build:lib
            yarn build:bin
            yarn "${{ matrix.cmd }}"
          fi

      - if: startsWith(github.ref, 'refs/tags/')
        name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: |
            ./build

  upload:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: result
          path: ./build
      - name: List
        run: find ./build -type f -not -path ./build/.gitignore
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/ts-playground-*
