name: Binary Release

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    # "released" events are emitted either when directly be released or be edited from pre-released.
    types: [prereleased, released]

jobs:
  build:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: install and build
        run: |
          pnpm install
          pnpm build

      - if: startsWith(github.ref, 'refs/tags/')
        name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: |
            ./build

  upload:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: result
          path: ./build
      - name: List
        run: find ./build -type f -not -path ./build/.gitignore
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/ts-playground-*
