name: Publish Typedoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publish Typedoc
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0

      - uses: actions/setup-node@v4
        with:
          # https://nodejs.org/en/about/previous-releases
          node-version: 22.x

      - run: pnpm install

      - run: |
          pnpm build
          pnpm typedoc

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/typedocs
          cname: ts-playground.typedoc.kitsuyui.com
