name: Publish Typedoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publish Typedoc
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: pnpm install

      - run: pnpm build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/typedocs
          cname: ts-playground.typedoc.kitsuyui.com
